'use client'

import { useMemo, useState } from 'react'
import { AlertTriangle, ArrowUpRight, BarChart3, Check, ChevronDown, CircleHelp, Clock3, CreditCard, FileText, Filter, LayoutDashboard, Menu, MoreHorizontal, RefreshCw, Search, Settings, Sparkles, Upload, UserRound, X } from 'lucide-react'

const rows = [
  { order: 'ORD-10482', customer: 'Oak & Pine Studio', date: 'Aug 30, 2026', amount: '$1,248.00', paid: '$1,248.00', status: 'Matched', delta: '$0.00' },
  { order: 'ORD-10481', customer: 'Morrow Goods', date: 'Aug 30, 2026', amount: '$892.50', paid: '$842.50', status: 'Mismatch', delta: '-$50.00' },
  { order: 'ORD-10480', customer: 'Cinder Supply Co.', date: 'Aug 29, 2026', amount: '$326.00', paid: '$326.00', status: 'Matched', delta: '$0.00' },
  { order: 'ORD-10479', customer: 'Verde Market', date: 'Aug 29, 2026', amount: '$2,140.75', paid: '$2,165.75', status: 'Mismatch', delta: '+$25.00' },
  { order: 'ORD-10478', customer: 'Northline Ceramics', date: 'Aug 28, 2026', amount: '$680.00', paid: '$680.00', status: 'Matched', delta: '$0.00' },
  { order: 'ORD-10477', customer: 'Aster House', date: 'Aug 28, 2026', amount: '$418.20', paid: '$418.20', status: 'Matched', delta: '$0.00' },
]
const nav = [{ label: 'Overview', icon: LayoutDashboard }, { label: 'Reconciliations', icon: RefreshCw, count: '3' }, { label: 'Discrepancies', icon: AlertTriangle, count: '3' }, { label: 'Reports', icon: BarChart3 }]

export default function Home() {
  const [active, setActive] = useState('Overview')
  const [status, setStatus] = useState('All statuses')
  const [search, setSearch] = useState('')
  const [selected, setSelected] = useState<typeof rows[number] | null>(null)
  const [uploaded, setUploaded] = useState(false)
  const [aiOpen, setAiOpen] = useState(false)
  const visibleRows = useMemo(() => rows.filter((row) => `${row.order} ${row.customer}`.toLowerCase().includes(search.toLowerCase()) && (status === 'All statuses' || row.status === status)), [search, status])

  return <div className="min-h-screen bg-background text-foreground">
    <aside className="fixed inset-y-0 left-0 z-20 hidden w-64 border-r bg-card lg:flex lg:flex-col">
      <div className="flex h-16 items-center gap-3 border-b px-6"><div className="flex size-8 items-center justify-center rounded-lg bg-primary text-primary-foreground"><Check className="size-4" /></div><span className="text-lg font-semibold tracking-tight">reconcile</span></div>
      <div className="flex flex-1 flex-col px-3 py-5"><p className="px-3 pb-3 text-xs font-medium uppercase tracking-wider text-muted-foreground">Workspace</p><nav className="flex flex-col gap-1">{nav.map(({ label, icon: Icon, count }) => <button key={label} onClick={() => setActive(label)} className={`flex items-center justify-between rounded-md px-3 py-2.5 text-sm transition-colors ${active === label ? 'bg-accent font-medium text-accent-foreground' : 'text-muted-foreground hover:bg-muted hover:text-foreground'}`}><span className="flex items-center gap-3"><Icon className="size-4" />{label}</span>{count && <span className="rounded-full bg-muted px-2 py-0.5 text-xs">{count}</span>}</button>)}</nav><div className="mt-auto flex flex-col gap-1"><button className="flex items-center gap-3 rounded-md px-3 py-2.5 text-sm text-muted-foreground hover:bg-muted"><Settings className="size-4" />Settings</button><button className="flex items-center gap-3 rounded-md px-3 py-2.5 text-sm text-muted-foreground hover:bg-muted"><CircleHelp className="size-4" />Help center</button></div></div>
      <div className="border-t p-4"><div className="flex items-center gap-3"><div className="flex size-8 items-center justify-center rounded-full bg-secondary text-xs font-medium">JD</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">Jordan Davis</p><p className="truncate text-xs text-muted-foreground">jordan@acme.co</p></div><MoreHorizontal className="size-4 text-muted-foreground" /></div></div>
    </aside>
    <main className="lg:pl-64"><header className="flex h-16 items-center justify-between border-b bg-card px-5 lg:px-8"><div className="flex items-center gap-3"><button className="lg:hidden"><Menu className="size-5" /></button><div><p className="text-sm font-medium">Acme Co.</p><p className="text-xs text-muted-foreground">Finance workspace</p></div></div><div className="flex items-center gap-3"><span className="hidden items-center gap-2 text-sm text-muted-foreground sm:flex"><Clock3 className="size-4" />Last synced 2m ago</span><button className="flex size-8 items-center justify-center rounded-full border bg-background text-muted-foreground"><UserRound className="size-4" /></button></div></header>
      <div className="mx-auto max-w-[1440px] p-5 lg:p-8"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-sm text-muted-foreground">Sunday, August 31, 2026</p><h1 className="text-2xl font-semibold tracking-tight">Good morning, Jordan</h1><p className="mt-1 text-sm text-muted-foreground">Here&apos;s what&apos;s happening with your payments.</p></div><div className="flex gap-2"><button onClick={() => setUploaded(true)} className="inline-flex items-center gap-2 rounded-md border bg-card px-3 py-2 text-sm font-medium shadow-sm hover:bg-muted"><Upload className="size-4" />Upload files</button><button className="inline-flex items-center gap-2 rounded-md bg-primary px-3 py-2 text-sm font-medium text-primary-foreground shadow-sm hover:opacity-90"><RefreshCw className="size-4" />Run reconciliation</button></div></div>
        {uploaded && <div className="mb-6 flex items-center justify-between rounded-md border border-primary/20 bg-accent px-4 py-3 text-sm"><span className="flex items-center gap-2"><Check className="size-4 text-primary" />Files uploaded. Ready to reconcile 1,284 transactions.</span><button onClick={() => setUploaded(false)}><X className="size-4 text-muted-foreground" /></button></div>}
        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={FileText} label="Total orders" value="1,284" hint="+8.4%" detail="vs. last period" /><Metric icon={CreditCard} label="Total processed" value="$186,420.50" hint="+12.6%" detail="vs. last period" /><Metric icon={Check} label="Matched" value="97.8%" hint="+1.2%" detail="vs. last period" /><Metric icon={AlertTriangle} label="Discrepancies" value="28" hint="-$1,240.00" detail="needs attention" warning /></section>
        <section className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_1fr]"><div className="rounded-lg border bg-card"><div className="flex items-start justify-between border-b p-5"><div><h2 className="font-semibold">Reconciliation overview</h2><p className="mt-1 text-sm text-muted-foreground">Order value vs. payments received</p></div><button className="flex items-center gap-1 rounded-md border px-2.5 py-1.5 text-xs text-muted-foreground">Last 30 days <ChevronDown className="size-3" /></button></div><div className="p-5"><div className="mb-5 flex items-center gap-5 text-xs text-muted-foreground"><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-primary" />Order value</span><span className="flex items-center gap-2"><i className="size-2 rounded-full bg-secondary-foreground/40" />Payments received</span></div><div className="flex h-48 items-end gap-2 border-b border-l px-2 pt-5 sm:gap-4">{[52,68,48,76,62,84,74,92,70,88,78,96,86,98].map((height, i) => <div key={i} className="flex flex-1 items-end gap-0.5"><div className="w-1/2 rounded-t-sm bg-primary/80" style={{ height: `${height}%` }} /><div className="w-1/2 rounded-t-sm bg-secondary-foreground/15" style={{ height: `${height - 8}%` }} /></div>)}</div><div className="flex justify-between pt-3 text-[11px] text-muted-foreground"><span>Aug 1</span><span>Aug 8</span><span>Aug 15</span><span>Aug 22</span><span>Aug 30</span></div></div></div><div className="rounded-lg border bg-card"><div className="border-b p-5"><h2 className="font-semibold">Needs attention</h2><p className="mt-1 text-sm text-muted-foreground">Items that need your review</p></div><div className="flex flex-col">{[{title:'Underpayment detected', sub:'ORD-10481 · $50.00 difference', tone:'danger'},{title:'Overpayment detected', sub:'ORD-10479 · $25.00 difference', tone:'warning'},{title:'Missing transaction', sub:'ORD-10474 · No processor match', tone:'danger'}].map(item => <button key={item.title} onClick={() => setSelected(rows.find(r => r.order === item.sub.split(' · ')[0]) || rows[1])} className="flex items-center gap-3 border-b p-4 text-left last:border-0 hover:bg-muted/60"><div className={`flex size-8 items-center justify-center rounded-full ${item.tone === 'danger' ? 'bg-destructive/10 text-destructive' : 'bg-warning/15 text-warning-foreground'}`}><AlertTriangle className="size-4" /></div><div className="min-w-0 flex-1"><p className="text-sm font-medium">{item.title}</p><p className="truncate text-xs text-muted-foreground">{item.sub}</p></div><ArrowUpRight className="size-4 text-muted-foreground" /></button>)}</div><button onClick={() => setActive('Discrepancies')} className="m-4 mt-0 flex items-center justify-center rounded-md border py-2 text-sm font-medium hover:bg-muted">View all discrepancies</button></div></section>
        <section className="mt-6 rounded-lg border bg-card"><div className="flex flex-col justify-between gap-4 border-b p-5 lg:flex-row lg:items-center"><div><h2 className="font-semibold">Recent transactions</h2><p className="mt-1 text-sm text-muted-foreground">Review your latest order and payment matches.</p></div><div className="flex flex-wrap gap-2"><div className="flex items-center gap-2 rounded-md border px-3 py-2"><Search className="size-4 text-muted-foreground" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search orders..." className="w-32 bg-transparent text-sm outline-none placeholder:text-muted-foreground sm:w-44" /></div><button className="flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><Filter className="size-4" />Filter</button><select value={status} onChange={e => setStatus(e.target.value)} className="rounded-md border bg-card px-3 py-2 text-sm"><option>All statuses</option><option>Matched</option><option>Mismatch</option></select></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-muted/50 text-xs text-muted-foreground"><tr>{['Order','Customer','Date','Order total','Amount paid','Status','Difference',''].map(h => <th key={h} className="px-5 py-3 font-medium">{h}</th>)}</tr></thead><tbody>{visibleRows.map(row => <tr key={row.order} onClick={() => setSelected(row)} className="cursor-pointer border-t transition-colors hover:bg-muted/40"><td className="px-5 py-4 font-medium">{row.order}</td><td className="px-5 py-4">{row.customer}</td><td className="px-5 py-4 text-muted-foreground">{row.date}</td><td className="px-5 py-4">{row.amount}</td><td className="px-5 py-4">{row.paid}</td><td className="px-5 py-4"><Status status={row.status} /></td><td className={`px-5 py-4 font-medium ${row.delta !== '$0.00' ? 'text-destructive' : 'text-muted-foreground'}`}>{row.delta}</td><td className="px-5 py-4"><MoreHorizontal className="size-4 text-muted-foreground" /></td></tr>)}</tbody></table></div><div className="flex items-center justify-between border-t px-5 py-3 text-xs text-muted-foreground"><span>Showing {visibleRows.length} of 1,284 transactions</span><div className="flex gap-1"><button className="rounded border px-2 py-1 opacity-50">Previous</button><button className="rounded border px-2 py-1 hover:bg-muted">Next</button></div></div></section>
        <section className="mt-6 flex flex-col items-start justify-between gap-4 rounded-lg border bg-primary p-5 text-primary-foreground sm:flex-row sm:items-center"><div><div className="mb-1 flex items-center gap-2 text-sm font-medium"><Sparkles className="size-4" />AI reconciliation assistant</div><p className="text-sm text-primary-foreground/75">Get a plain-English explanation of your discrepancies and suggested next steps.</p></div><button onClick={() => setAiOpen(true)} className="whitespace-nowrap rounded-md bg-card px-3 py-2 text-sm font-medium text-foreground hover:bg-background">Analyze discrepancies</button></section>
      </div>
    </main>
    {selected && <div className="fixed inset-0 z-30 flex items-end justify-end bg-foreground/20 p-0 sm:p-6"><div className="flex h-full w-full max-w-lg flex-col bg-card shadow-xl sm:h-auto sm:max-h-[calc(100vh-48px)] sm:rounded-lg"><div className="flex items-start justify-between border-b p-5"><div><p className="text-xs text-muted-foreground">Transaction detail</p><h2 className="mt-1 text-xl font-semibold">{selected.order}</h2></div><button onClick={() => setSelected(null)} className="rounded-md p-1 hover:bg-muted"><X className="size-5" /></button></div><div className="flex flex-col gap-5 overflow-y-auto p-5"><Status status={selected.status} /><div className="grid grid-cols-2 gap-4">{[['Customer',selected.customer],['Date',selected.date],['Order total',selected.amount],['Amount paid',selected.paid]].map(([label,value]) => <div key={label}><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div>)}</div><div className="rounded-md bg-muted/60 p-4"><p className="text-sm font-medium">Why this was flagged</p><p className="mt-2 text-sm leading-6 text-muted-foreground">The order total and processor settlement differ by <span className="font-medium text-foreground">{selected.delta}</span>. Review the payment record and any refunds, fees, or manual adjustments.</p></div><button onClick={() => setAiOpen(true)} className="flex items-center justify-center gap-2 rounded-md border py-2.5 text-sm font-medium hover:bg-muted"><Sparkles className="size-4" />Explain with AI</button></div></div></div>}
    {aiOpen && <div className="fixed inset-0 z-40 flex items-center justify-center bg-foreground/30 p-5"><div className="w-full max-w-md rounded-lg bg-card p-6 shadow-xl"><div className="flex items-start justify-between"><div><div className="flex items-center gap-2 text-sm font-medium"><Sparkles className="size-4 text-primary" />AI analysis</div><h2 className="mt-2 text-xl font-semibold">3 discrepancies found</h2></div><button onClick={() => setAiOpen(false)}><X className="size-5 text-muted-foreground" /></button></div><p className="mt-4 text-sm leading-6 text-muted-foreground">Most of the difference comes from an underpayment on ORD-10481. The remaining items look like a processor fee adjustment and one missing transaction. Check the settlement report before posting a journal entry.</p><div className="mt-5 flex justify-end gap-2"><button onClick={() => setAiOpen(false)} className="rounded-md border px-3 py-2 text-sm">Close</button><button onClick={() => setAiOpen(false)} className="rounded-md bg-primary px-3 py-2 text-sm text-primary-foreground">View report</button></div></div></div>}
  </div>
}
function Metric({ icon: Icon, label, value, hint, detail, warning }: { icon: typeof Check; label: string; value: string; hint: string; detail: string; warning?: boolean }) { return <div className="rounded-lg border bg-card p-5"><div className="flex items-center justify-between"><span className="text-sm text-muted-foreground">{label}</span><Icon className={`size-4 ${warning ? 'text-warning-foreground' : 'text-muted-foreground'}`} /></div><div className="mt-3 flex items-baseline gap-2"><span className="text-2xl font-semibold tracking-tight">{value}</span><span className={`text-xs font-medium ${warning ? 'text-destructive' : 'text-primary'}`}>{hint}</span></div><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div> }
function Status({ status }: { status: string }) { return <span className={`inline-flex rounded-full px-2 py-1 text-xs font-medium ${status === 'Matched' ? 'bg-primary/10 text-primary' : 'bg-destructive/10 text-destructive'}`}>{status}</span> }
